# Shell variables
# Generated by 'wal'
wallpaper='/Users/sc/Handle1_diff.png'




foreground='#e8e8e8'
foreground_bold='#e8e8e8'
cursor='#e8e8e8'
background='#333333'
color0='#2e2e2e'
color8='#2e2e2e'
color1='#eb4129'
color9='#eb4129'
color2='#abe047'
color10='#abe047'
color3='#f6c744'
color11='#f6c744'
color4='#f66f3f'
color12='#f66f3f'
color5='#ff45bb'
color13='#ff45bb'
color6='#64dbed'
color14='#64dbed'

# white
color7=#e8e8e8
color15=#e8e8e8

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
